In [30]:
import pandas as pd
import pandas as pd
import json
import numpy as np
import requests as r
paris = pd.read_csv('listings.csv')
#Checking out the data
paris.head(100)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,3109,zen and calm,3631,Anne,NaN,Observatoire,48.83349,2.31852,Entire home/apt,60,3,8,2018-12-19,0.26,1,227
1,5396,Explore the heart of old Paris,7903,Borzou,NaN,Hôtel-de-Ville,48.85100,2.35869,Entire home/apt,115,1,180,2019-06-21,1.47,1,27
2,7397,MARAIS - 2ROOMS APT - 2/4 PEOPLE,2626,Franck,NaN,Hôtel-de-Ville,48.85758,2.35275,Entire home/apt,115,10,248,2019-06-25,2.47,1,240
3,7964,Large & sunny flat with balcony !,22155,Anaïs,NaN,Opéra,48.87464,2.34341,Entire home/apt,130,6,6,2015-09-14,0.05,1,302
4,8522,GREAT FLAT w/ CITY VIEW,25435,Adrien,NaN,Ménilmontant,48.86528,2.39326,Entire home/apt,90,3,1,2010-06-16,0.01,1,186
5,9359,"Cozy, Central Paris: WALK or VELIB EVERYWHERE !",28422,Bernadette,NaN,Louvre,48.85899,2.34735,Entire home/apt,75,180,0,NaN,NaN,1,99
6,9952,Paris petit coin douillet,33534,Elisabeth,NaN,Popincourt,48.86227,2.37134,Entire home/apt,75,5,20,2019-07-05,0.26,1,289
7,10586,BAIL MOBILITE Montmartre Studio 7,37107,Michael,NaN,Buttes-Montmartre,48.88902,2.34656,Entire home/apt,80,30,43,2019-06-30,0.37,3,209
8,10588,Montmartre Studio 10,37107,Michael,NaN,Buttes-Montmartre,48.88918,2.34490,Entire home/apt,75,30,16,2016-10-01,0.16,3,0
9,10710,"Calm place in a ""bourgeois"" area !",38170,Josiane,NaN,Élysée,48.87900,2.31608,Entire home/apt,90,3,40,2019-01-25,0.35,1,203
10,11170,QUARTIER LATIN APART,40963,Léna,NaN,Panthéon,48.84670,2.35095,Entire home/apt,75,2,343,2019-07-07,2.88,1,188
11,11213,DOWNTOWN PARIS,41322,Mathieu,NaN,Entrepôt,48.87110,2.37424,Entire home/apt,157,1,121,2019-06-26,2.47,2,342
12,11265,Elegant appartment in Montmartre,41718,Sylvie,NaN,Buttes-Montmartre,48.88434,2.34005,Entire home/apt,100,7,14,2019-07-02,0.37,1,226
13,11798,Loft very charming in Paris,44444,Laurence,NaN,Gobelins,48.82405,2.36828,Entire home/apt,110,2,80,2019-06-20,0.97,1,348
14,11848,Swishy Cosy Paris Pad,44626,Thierry,NaN,Popincourt,48.86578,2.37705,Entire home/apt,79,30,319,2019-07-07,3.03,1,255
15,12268,Faubourg Saint Antoine-chambrecalme,47196,Charles,NaN,Popincourt,48.85090,2.38695,Private room,60,6,1,2010-05-28,0.01,2,0
16,12452,De Place Voltaire à Chemin vert. Paris 11ème,48733,Irene,NaN,Popincourt,48.85909,2.37704,Entire home/apt,100,5,11,2019-03-03,0.76,1,5
17,14264,Charming sunny 2BR in Montmartre !,55995,Lara,NaN,Buttes-Montmartre,48.88315,2.34158,Entire home/apt,110,7,10,2019-05-05,0.13,1,180
18,14757,Lovely Studio Montmartre,57954,Nolwenn,NaN,Buttes-Montmartre,48.89052,2.34453,Entire home/apt,75,3,200,2019-01-19,1.95,1,160
19,16048,Absolute Paris 2 pièces 40 m²,62642,Luis,NaN,Buttes-Chaumont,48.89083,2.37347,Entire home/apt,75,5,2,2013-03-15,0.03,1,54
20,16455,"Spacious, Light-Filled Apartment",64054,David,NaN,Gobelins,48.83616,2.36323,Entire home/apt,55,4,24,2019-07-08,0.39,2,19
21,16457,***ROOFTOP LE MARAIS***,64057,Carole,NaN,Hôtel-de-Ville,48.85339,2.36284,Entire home/apt,78,5,340,2019-05-10,3.00,1,61
22,16626,Luxury in St Michel,64627,Phoenice,NaN,Luxembourg,48.85324,2.34171,Private room,120,5,70,2019-06-23,0.61,3,326
23,17283,Charming Appartment Goncourt Paris,67010,Sandra,NaN,Entrepôt,48.87033,2.37152,Entire home/apt,105,2,59,2019-04-25,0.71,3,190
24,17316,BEAUTIFUL APT IN PARIS CANAL ST MAR,67192,Frank,NaN,Entrepôt,48.87217,2.36206,Entire home/apt,80,120,1,2018-08-01,0.09,1,0
25,17918,Big Flat in Paris with a retro feel,20633,Patrick,NaN,Opéra,48.88282,2.33272,Entire home/apt,110,2,3,2018-11-03,0.03,2,191
26,17919,A Room in Paris 9e Pigalle,20633,Patrick,NaN,Opéra,48.88327,2.33292,Private room,65,1,124,2019-07-08,1.12,2,161
27,17994,Center of paris: Louvre,69389,Reem,NaN,Louvre,48.86093,2.34254,Entire home/apt,250,2,155,2019-07-04,1.35,1,350
28,19150,LOVELY APARTMENT NEAR MONTMARTRE,71496,Stephanie,NaN,Buttes-Montmartre,48.88565,2.35906,Entire home/apt,80,3,2,2011-06-27,0.02,1,0
29,19306,PARIS ROMANTIC MAISONETTE,73530,Marie,NaN,Panthéon,48.83872,2.35297,Entire home/apt,98,2,202,2019-06-22,1.78,3,239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,35697,Very nice flat batignolles district,153430,Claire,NaN,Batignolles-Monceau,48.88743,2.31811,Entire home/apt,115,2,1,2018-07-12,0.08,1,15
71,36267,Titon FaubourgSaint-AntoineBastille,47196,Charles,NaN,Popincourt,48.85145,2.38703,Entire home/apt,110,6,15,2015-12-31,0.14,2,0
72,36490,Low budget in a residential area,156936,Christian,NaN,Reuilly,48.83613,2.40176,Private room,32,3,87,2019-01-18,0.82,1,0
73,36586,Charming sunny 1BR Buttes Chaumont,157430,Stephanie,NaN,Buttes-Chaumont,48.88047,2.39408,Entire home/apt,50,3,36,2018-12-08,0.36,1,129
74,36868,Great family size apt near park !,159102,Philippe,NaN,Buttes-Chaumont,48.88257,2.38782,Entire home/apt,1800,1,29,2017-11-06,0.27,1,89
75,37801,EIFFEL TOWER QUALITY STAY,112192,Marc,NaN,Vaugirard,48.84106,2.28245,Entire home/apt,94,6,49,2014-04-24,0.45,1,153
76,38303,Charming Flat on the roof,146581,Antoine,NaN,Popincourt,48.86511,2.36675,Private room,50,10,20,2018-11-13,0.19,1,0
77,38871,"Special promotion for ""Stylish and convenient""",166743,Monica,NaN,Gobelins,48.83344,2.34601,Entire home/apt,99,3,217,2019-07-06,2.39,1,191
78,39651,Charming Studio close to Bastille,170325,Carole,NaN,Popincourt,48.84930,2.39022,Entire home/apt,59,5,38,2018-08-30,0.35,1,74
79,39666,Paris 5 Star Luxury on the Ile Saint-Louis,170397,Judith,NaN,Hôtel-de-Ville,48.85172,2.35504,Entire home/apt,921,2,36,2019-07-06,0.36,1,273
80,39716,GEORGEOUS 2 Bedroom in Montmartre,170600,Jean Michel,NaN,Buttes-Montmartre,48.88745,2.34695,Entire home/apt,140,2,346,2019-06-26,3.20,1,6
81,39948,COSY INDEPENDENT ROOM IN CENTRAL PARIS,171483,Aliyah & Philippe,NaN,Bourse,48.87064,2.34510,Entire home/apt,90,4,57,2019-06-23,0.81,1,285
82,40143,Stylish & Design 1BR flat- Voltaire Bastille,172322,Emmanuelle,NaN,Popincourt,48.85672,2.37771,Entire home/apt,139,7,11,2017-04-16,0.10,1,0
83,40174,"Great, central Paris rental!",172460,Leila,NaN,Hôtel-de-Ville,48.85362,2.36336,Entire home/apt,95,2,79,2019-06-19,0.77,1,303
84,40775,Great Flat to Rent in Paris Center,176060,Sophie,NaN,Popincourt,48.86375,2.37586,Entire home/apt,75,10,81,2018-08-13,0.79,1,76
85,40899,Lovely flat Canal Saint Martin,177130,Lola,NaN,Entrepôt,48.87549,2.37224,Entire home/apt,75,4,70,2019-06-23,1.35,1,255
86,40911,The White & Cosy Flat,177212,David,NaN,Batignolles-Monceau,48.88787,2.31093,Entire home/apt,105,5,9,2015-01-05,0.09,1,23
87,41077,Bed&Breakfast The Welcoming Dragon,178239,Philipp,NaN,Gobelins,48.82515,2.36270,Private room,98,3,6,2018-06-22,0.06,1,250
88,41106,"STYLE&COMFORT@LE MARAIS, what else?",177387,LetsgetSirius,NaN,Hôtel-de-Ville,48.85768,2.35545,Entire home/apt,175,4,75,2019-06-17,0.70,1,0
89,41745,Charmant loft en duplex au calme da,182588,Maxence,NaN,Popincourt,48.86930,2.37163,Entire home/apt,79,5,9,2018-05-20,0.12,2,296
90,42348,tres beau studio à trés bon PRIX,184942,Max,NaN,Opéra,48.87830,2.33966,Entire home/apt,75,3,79,2019-06-25,1.00,1,241
91,42507,"Calm, Renovated, Equipped, on the Canal & Metro",142478,Yael,NaN,Buttes-Chaumont,48.88868,2.37544,Entire home/apt,78,3,51,2019-04-08,0.51,1,0
92,43027,Montmartre by foot ! Beautiful & cosy 70m2,187799,Charlotte,NaN,Buttes-Montmartre,48.88747,2.32604,Entire home/apt,150,3,63,2019-03-24,0.59,1,363
93,43219,Cozy 2 bdr Loft apartment in Paris,188624,Sylvie,NaN,Popincourt,48.86579,2.37937,Entire home/apt,140,5,10,2015-07-10,0.14,1,189
94,43355,STUDIO REPUBLIQUE CANAL ST MARTIN,187798,Chris,NaN,Entrepôt,48.86965,2.36719,Entire home/apt,60,28,8,2019-06-08,0.11,1,2
95,43500,MONTMARTRE SACRE COEUR,152242,Delphine,NaN,Buttes-Montmartre,48.88487,2.34445,Entire home/apt,155,6,2,2018-07-20,0.03,6,360
96,44123,Le Marais - L'île St-Louis,152242,Delphine,NaN,Hôtel-de-Ville,48.85329,2.35978,Entire home/apt,215,3,47,2019-06-24,0.45,6,291
97,44198,Paris's Heart Peaceful Duplex 43m2,193617,Edith,NaN,Entrepôt,48.87095,2.35622,Entire home/apt,92,2,27,2015-09-07,0.25,2,198
98,45175,Appartement XIX century near Buttes,199617,Simone,NaN,Buttes-Chaumont,48.87564,2.38717,Private room,63,3,0,NaN,NaN,1,0
99,45630,room in anice 40m2 flat/great view!,202804,Regis,NaN,Buttes-Montmartre,48.89078,2.36010,Private room,34,3,58,2019-06-11,0.54,2,88

In [31]:
#Noticed was that the neighbourhood_group column contained a lot of nulls
paris['neighbourhood_group'].isnull().value_counts()

True    64293
Name: neighbourhood_group, dtype: int64

In [32]:
#Found it unnecessary
paris = paris.drop(['neighbourhood_group'],axis=1)

In [33]:
#Checking how many values are in each column and how they're represented to clean them
print(paris.isnull().sum(),'\n')
paris['host_name'] = paris['host_name'].fillna('N/A')
paris['name'] = paris['name'].fillna('N/A')
paris['last_review'] = paris['last_review'].fillna('N/A')
paris['reviews_per_month'] = paris['reviews_per_month'].fillna(0)
print(paris.isnull().sum())
# paris.to_json(orient='index')

id                                    0
name                                 69
host_id                               0
host_name                            64
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       14609
reviews_per_month                 14609
calculated_host_listings_count        0
availability_365                      0
dtype: int64

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [34]:
paris.head()

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,3109,zen and calm,3631,Anne,Observatoire,48.83349,2.31852,Entire home/apt,60,3,8,2018-12-19,0.26,1,227
1,5396,Explore the heart of old Paris,7903,Borzou,Hôtel-de-Ville,48.85100,2.35869,Entire home/apt,115,1,180,2019-06-21,1.47,1,27
2,7397,MARAIS - 2ROOMS APT - 2/4 PEOPLE,2626,Franck,Hôtel-de-Ville,48.85758,2.35275,Entire home/apt,115,10,248,2019-06-25,2.47,1,240
3,7964,Large & sunny flat with balcony !,22155,Anaïs,Opéra,48.87464,2.34341,Entire home/apt,130,6,6,2015-09-14,0.05,1,302
4,8522,GREAT FLAT w/ CITY VIEW,25435,Adrien,Ménilmontant,48.86528,2.39326,Entire home/apt,90,3,1,2010-06-16,0.01,1,186

In [35]:
paris.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [36]:
len(paris['last_review'].unique())

1812

In [37]:
paris['last_review'] = pd.to_datetime(paris['last_review'], errors='coerce')
paris['last_review']

0       2018-12-19
1       2019-06-21
2       2019-06-25
3       2015-09-14
4       2010-06-16
           ...
64288          NaT
64289          NaT
64290          NaT
64291          NaT
64292          NaT
Name: last_review, Length: 64293, dtype: datetime64[ns]

In [38]:
paris.to_json('../Data/ParisBNBs.json',orient='records')

In [39]:
import geopandas as gpd
df = gpd.read_file('neighbourhoods.geojson')
df

,neighbourhood,neighbourhood_group,geometry
0,Batignolles-Monceau,None,"(POLYGON ((2.295167 48.873955, 2.29504 48.8737..."
1,Palais-Bourbon,None,"(POLYGON ((2.320903 48.863057, 2.320941 48.863..."
2,Buttes-Chaumont,None,"(POLYGON ((2.389429 48.901218, 2.390136 48.901..."
3,Opéra,None,"(POLYGON ((2.339777 48.882029, 2.339816 48.882..."
4,Entrepôt,None,"(POLYGON ((2.364686 48.884369, 2.364855 48.884..."
5,Gobelins,None,"(POLYGON ((2.374913 48.838009, 2.376983 48.836..."
6,Vaugirard,None,"(POLYGON ((2.299322 48.852174, 2.300884 48.851..."
7,Reuilly,None,"(POLYGON ((2.41388 48.833571, 2.414007 48.8335..."
8,Louvre,None,"(POLYGON ((2.328007 48.869917, 2.329966 48.868..."
9,Luxembourg,None,"(POLYGON ((2.344593 48.854049, 2.344284 48.853..."
10,Élysée,None,"(POLYGON ((2.325836 48.869562, 2.325687 48.869..."
11,Temple,None,"(POLYGON ((2.363828 48.867504, 2.363889 48.867..."
12,Ménilmontant,None,"(POLYGON ((2.412765 48.875474, 2.412836 48.875..."
13,Panthéon,None,"(POLYGON ((2.364433 48.84614, 2.364836 48.8458..."
14,Passy,None,"(POLYGON ((2.274268 48.878365, 2.277491 48.877..."
15,Observatoire,None,"(POLYGON ((2.333807 48.840609, 2.336729 48.839..."
16,Popincourt,None,"(POLYGON ((2.396237 48.854155, 2.397075 48.853..."
17,Bourse,None,"(POLYGON ((2.351518 48.864426, 2.350949 48.863..."
18,Buttes-Montmartre,None,"(POLYGON ((2.365804 48.885544, 2.364686 48.884..."
19,Hôtel-de-Ville,None,"(POLYGON ((2.368512 48.855734, 2.369003 48.853..."

In [71]:
paris['availability_365'].corr(paris['reviews_per_month'])

0.18130987628317696

In [42]:
# Cities = round(paris.groupby(['neighbourhood'])['price','availability_365','number_of_reviews'].mean(),0)

In [69]:
Cities = round(paris.pivot_table(index=["neighbourhood"], values=['price','availability_365','number_of_reviews'], aggfunc=[np.mean,min,max]),2)                    
C1 = Cities.iloc[:,0:3]
C2 = Cities.iloc[:,5:6]
C3 = Cities.iloc[:,8:]
Cities = pd.concat([C1,C2,C3],axis =1)
Cities.to_csv('../Data/Cities.csv') 
Cities

                                mean                             min   max
                    availability_365 number_of_reviews   price price price
neighbourhood
Batignolles-Monceau            77.38             13.38  107.65    10  2000
Bourse                        121.91             30.44  146.70    19  5150
Buttes-Chaumont                63.23             12.76   79.56     0  5000
Buttes-Montmartre              63.12             16.75   86.26     0  9379
Entrepôt                       71.24             20.19  101.45     9  2000
Gobelins                       68.25             16.37   82.07     0  1000
Hôtel-de-Ville                115.88             29.04  157.26    10  3183
Louvre                        125.01             27.31  177.90     9  8000
Luxembourg                    116.72             25.66  175.27     9  1610
Ménilmontant                   61.41             13.42   74.15    10  1500
Observatoire                   74.69             15.79  100.86     9  8921
Opéra                          86.61             18.70  135.03     9  1898
Palais-Bourbon                110.86             23.04  182.46    10  3000
Panthéon                       98.49             24.90  129.73    10  2200
Passy                         112.49             15.52  164.83     0  8721
Popincourt                     66.64             17.99   91.82     0  8288
Reuilly                        70.37             16.42   88.49     0  3325
Temple                        115.73             26.21  154.67     0  8500
Vaugirard                      73.82             17.78  108.10     0  8576
Élysée                        138.98             18.86  240.17    12  5000

In [72]:
paris.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood', 'latitude',
       'longitude', 'room_type', 'price', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365'],
      dtype='object')

In [75]:
(paris['availability_365']/12).mean()

6.970109498701258